name: 'Build and Push Docker Image'
description: 'Build and push Docker image to GHCR'
inputs:
  dockerfile:
    description: 'Dockerfile path'
    required: true
  tag:
    description: 'Image tag'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      shell: bash

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: true
        platforms: linux/amd64
        tags: |
          ghcr.io/${{ github.repository_owner }}/patchright:${{ inputs.tag }}
        provenance: false
        sbom: false
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.description=HTTP Server
          org.opencontainers.image.licenses=MIT
        cache-from: type=gha
        cache-to: type=gha,mode=max
      shell: bash